"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@components/components/Header/header";
import Footer from "@components/components/Footer/footer";
import "./globals.css";
import { Plus_Jakarta_Sans } from 'next/font/google';
import "@components/icons/fontawesome"; 
import React, { useState } from "react";
import WaitlistModal from "@components/components/modal/JoinWaitlistModal";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700', '800' ], // Add any weights you plan to use
  variable: '--font-jakarta',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [modalOpen, setModalOpen] = useState(false);
  return (
    <html lang="en" className={plusJakarta.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header onJoinClick={() => setModalOpen(true)} />
        <main>{children}</main>
        <WaitlistModal isOpen={modalOpen} onClose={() => setModalOpen(false)} />
        <Footer />
      </body>
    </html>
  );
}
